import localFont from 'next/font/local';
import './globals.css';
import { Navbar } from './ui/home/navbar/navbar';
import { Footer } from './ui/home/footer/footer';




const sfui = localFont({
  src: [
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-ultralight-58646b19bf205.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-ultralight-58646b19bf205.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-light-58646b33e0551.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-medium-58646be638f96.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-semibold-58646eddcae92.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-bold-58646a511e3d9.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-heavy-586470160b9e5.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/sf-ui-display/sf-ui-display-black-58646a6b80d5a.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--sfui-font",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={sfui.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}

